env:
  browser: true
  es2020: true
  node: true
extends:
  - 'plugin:react/recommended'
  - google
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules: 
  complexity: ['error', 10]
  react/prop-types: off
  'no-unused-vars': off
  '@typescript-eslint/no-unused-vars': error
  prettier/prettier:
    - error